import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  contacts: [],
};

// Create Redux state slice
const contactsSlice = createSlice({
  name: 'contacts',
  initialState,

  reducers: {
    // Define reducers
    addContacts: (state, action) => {
      state.contacts = [...state.contacts, action.payload];
    },
    removeContacts: (state, action) => {
      state.contacts = state.contacts.filter(
        element => element.id !== action.payload
      );
    },
  },
});

export const { addContacts, removeContacts } = contactsSlice.actions;

// Export reducer generated by "createSlice()":
export default contactsSlice.reducer;
